broker-registrar 수정
deployment 파일, jobs/apimanager-broker, jobs/broker-registrar 수정

diff --git a/open-apiplatform-release/jobs/broker-registrar/templates/errand.sh.erb b/open-apiplatform-release/jobs/broker-registrar/templates/errand.sh.erb
--- a/open-apiplatform-release/jobs/broker-registrar/templates/errand.sh.erb
+++ b/open-apiplatform-release/jobs/broker-registrar/templates/errand.sh.erb
@@ -19,3 +19,36 @@ cf --version
 #cf create-service-broker $BROKER_NAME $BROKER_USERNAME $BROKER_PASSWORD $BROKER_URL || cf update-service-broker $BROKER_NAME $BROKER_USERNAME $BROKER_PASSWORD $BROKER_URL
 #cf enable-service-access $BROKER_NAME
 
+echo "CF_API_URL=${CF_API_URL}"
+echo "CF_SKIP_SSL_VALIDATION=${CF_SKIP_SSL_VALIDATION}"
+echo "CF_ADMIN_USERNAME=${CF_ADMIN_USERNAME}"
+echo "BROKER_NAME=${BROKER_NAME}"
+echo "BROKER_URL=${BROKER_URL}"
+echo "BROKER_USERNAME=${BROKER_USERNAME}"
+
+if [[ ${CF_SKIP_SSL_VALIDATION} == "true" ]]; then
+  cf api ${CF_API_URL} --skip-ssl-validation
+else
+  cf api ${CF_API_URL}
+fi
+
+cf auth \
+  ${CF_ADMIN_USERNAME} \
+  ${CF_ADMIN_PASSWORD}
+
+set +e
+OUTPUT=$( cf create-service-broker ${BROKER_NAME} ${BROKER_USERNAME} ${BROKER_PASSWORD} ${BROKER_URL} )
+EXIT_CODE=$?
+set -e
+
+if [[ ${EXIT_CODE} -ne 0  ]]; then
+  if [[ ${OUTPUT} == *"service broker name is taken"* ]]; then
+    echo "Service broker already exists - proceeding"
+  elif [[ ${OUTPUT} == *"service broker url is taken"* ]]; then
+    echo "Service broker already exists - proceeding"
+  else
+    echo "Unexpected failure: ${OUTPUT}"
+    exit 1
+  fi
+fi
+
